inventory_management/api/urls.py
# api/urls.py

from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import ProductViewSet, InventoryUpdateView, TransactionViewSet, ProductList, ProductDetail

router = DefaultRouter()
router.register(r'products', ProductViewSet, basename='product')
router.register(r'transactions', TransactionViewSet, basename='transaction')  # New endpoint for transactions

urlpatterns = [
    path('inventory/update/<int:pk>/', InventoryUpdateView.as_view(), name='inventory-update'),
    path('products/', ProductList.as_view(), name='product-list'),
    path('products/<int:pk>/', ProductDetail.as_view(), name='product-detail'),
    path('', include(router.urls)),
]

inventory_management/inventory/urls.py
# inventory/urls.py
from django.urls import path
from . import views


app_name = 'inventory'
urlpatterns = [
    path('', views.index, name='index'),


    path('family_list/', views.family_list, name='family_list'),
    path('subfamily_list/', views.subfamily_list, name='subfamily_list'),
    path('add_subfamily/', views.add_subfamily, name='add_subfamily'),
    path('subfamily/edit/<int:pk>/', views.edit_subfamily, name='edit_subfamily'),
    path('subfamily/delete/<int:pk>', views.delete_subfamily, name='delete_subfamily'),
    path('add_family/', views.add_family, name= 'add_family'),
    path('product_list/', views.product_list, name='product_list'),
    path('add_product/', views.add_product, name='add_product'),
    path('products/<int:pk>/edit/', views.edit_product, name='edit_product'),
    path('products/<int:pk>/delete/', views.delete_product, name='delete_product'),
    path('generate_label/<int:pk>/', views.generate_label, name='generate_label'),
    path('products/<int:pk>/print_label/', views.print_label, name='print_label'),

]

inventory_management/inventory_management/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('inventory.urls')),
    path('api/', include('api.urls')),
    
    path('', include ('srm.urls')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inventory_management/srm/urls.py
from django.urls import path
from . import views 

app_name = 'srm'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('add_supplier/', views.add_supplier, name='add_supplier'),
    path('supplier_list/', views.supplier_list, name='supplier_list'),




]

inventory_management/inventory/forms.py
# inventory/forms.py
from django import forms
from .models import product, family, subfamily
from srm.models import supplier



class FamilyForm(forms.ModelForm):
    class Meta:
        model = family
        fields = ['family_name']
        labels = {
            'family_name': 'Family Name',
        }
        widgets = {
            'family_name': forms.TextInput(attrs={'class': 'form-control'}),
        }

class SubFamilyForm(forms.ModelForm):
    class Meta:
        model = subfamily
        fields = ['subfamily_name']
        labels = {
            'subfamily_name': 'Subfamily Name',
            'family': 'Family',
        }
        widgets = {
            'subfamily_name': forms.TextInput(attrs={'class': 'form-control'}),
            'family': forms.Select(attrs={'class': 'form-control'}),
        }

    family = forms.ModelChoiceField(
        queryset=family.objects.all(),
        empty_label='Select a Family',
        label='Family',
        widget=forms.Select(attrs={'class': 'form-control'}),
    )

class SubFamilyEditForm(forms.ModelForm):
    class Meta:
        model= subfamily
        fields = ['subfamily_name','family']
        labels = {
            'subfamily_name': 'Subfamily Name',
            'family': 'Family',
        }
        widgets = {
            'subfamily_name': forms.TextInput(attrs={'class': 'form-control'}),
            'family': forms.Select(attrs={'class': 'form-control'}),
        }

    family = forms.ModelChoiceField(
            queryset=family.objects.all(),
            empty_label='Select a Family',
            label='Family',
            widget=forms.Select(attrs={'class': 'form-control'}),
    )

class ProductForm(forms.ModelForm):


    family = forms.ModelChoiceField(
            queryset=family.objects.all(),
            empty_label='Select a Category',
            label='family_name',
            widget= forms.Select(attrs={'class': 'form-control'}),
    )
    subfamily = forms.ModelChoiceField(
            queryset=subfamily.objects.all(),
            empty_label='Select a Sub-category',
            label='subfamily_name',
            widget= forms.Select(attrs={'class': 'form-control'}),
    )
    supplier = forms.ModelChoiceField(
            queryset=supplier.objects.all(),
            empty_label='Select a Supplier',
            label='supplier_name',
            widget= forms.Select(attrs={'class': 'form-control'}),
    )
    class Meta:
        model = product
        fields = ['product_name', 'product_price_sell', 'product_price_buy','product_reference', 'product_quantity' ]
        labels = {
            'product_name':'Name',
            'product_price_sell': 'Price Sell',
            'product_reference' : 'Ref',
            'product_price_buy' : 'Price Buy',
            'product_quantity' : 'Quantity',

            }
        widgets = {
            'product_name': forms.TextInput(attrs={'class':'form-control'}),
            #'product_size':  forms.TextInput(attrs={'class':'form-control'}),
            #'color':  forms.TextInput(attrs={'class':'form-control'}),
            'product_price_sell': forms.TextInput(attrs={'class':'form-control'}),
            'product_price_buy' : forms.TextInput(attrs={'class':'form-control'}),
            'product_reference' :forms.TextInput(attrs={'class':'form-control'}),
            'product_quantity' : forms.TextInput(attrs={'class':'form-control'}),
        }

inventory_management/inventory/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import product, family, subfamily
from srm.models import supplier
from .forms import ProductForm, FamilyForm, SubFamilyForm, SubFamilyEditForm

#import logging
from django.http import HttpResponseBadRequest
from barcode.writer import ImageWriter
from .utils import generate_sku
from PIL import Image, ImageDraw, ImageFont
from django.http import HttpResponse
from barcode import Code128
from io import BytesIO
import base64
from barcode.errors import BarcodeError
import os
from django.conf import settings
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas






#index:
def index(request):
    return render(request,'inventory/index.html')

#family_list:
def family_list(request):
    families = family.objects.all()
    return render(request,'inventory/family_list.html', {'families': families})

#subfamily_list
def subfamily_list(request):
    subfamilies = subfamily.objects.all()
    return render(request, 'inventory/subfamily_list.html', {'subfamilies': subfamilies})


#add_family:
def add_family(request):
    if request.method == 'POST':
        family_form = FamilyForm(request.POST)
        if family_form.is_valid():
            family_form.save()
            return redirect('inventory:family_list')
    else:
        family_form = FamilyForm()
    return render(request, 'inventory/add_family.html',{'family_form':family_form})

#logger = logging.getLogger(__name__)

def add_subfamily(request):
    if request.method == 'POST':
        subfamily_form = SubFamilyForm(request.POST, prefix='subfamily')
        #logger.error(request.POST)  # Logging line

        if subfamily_form.is_valid():
            subfamily_instance = subfamily_form.save(commit=False)

            # Get the family instance ID from the form data
            family_instance_id = request.POST.get('subfamily-family')
            #logger.error(f"Family instance ID: {family_instance_id}")  # Logging line

            if family_instance_id is None:
                return HttpResponseBadRequest("Missing 'subfamily-family' field in form data.")

            # Retrieve the corresponding family instance
            family_instance = get_object_or_404(family, pk=family_instance_id)

            subfamily_instance.family = family_instance
            subfamily_instance.save()
            return redirect('inventory:family_list')  # Redirect wherever appropriate

    else:
        subfamily_form = SubFamilyForm(prefix='subfamily')

    return render(request, 'inventory/add_subfamily.html', {'subfamily_form': subfamily_form})

#Product_list:
def product_list(request):
    products = product.objects.all()
    return render(request,'inventory/product_list.html', {'products': products})

#add_product:


def add_product(request):
    if request.method == 'POST':
        product_form = ProductForm(request.POST, prefix='product')
        if product_form.is_valid():
            family_id = request.POST.get('product-family')
            subfamily_id = request.POST.get('product-subfamily')
            supplier_id = request.POST.get('product-supplier')

            try:
                family_instance = family.objects.get(pk=family_id)
            except family.DoesNotExist:
                print(f"DEBUG: Family with ID {family_id} does not exist.")
                return HttpResponseBadRequest("Selected family does not exist.")

            try:
                subfamily_instance = subfamily.objects.get(pk=subfamily_id)
            except subfamily.DoesNotExist:
                print(f"DEBUG: SubFamily with ID {subfamily_id} does not exist.")
                return HttpResponseBadRequest("Selected subfamily does not exist.")
            try:
                supplier_instance = supplier.objects.get(pk=supplier_id)
            except supplier.DoesNotExist:
                print(f"DEBUG: Supplier with ID {supplier_id} does not exist.")
                return HttpResponseBadRequest("Selected supplier does not exist.")
            

            product_instance = product_form.save(commit=False)
            product_instance.family = family_instance
            product_instance.subfamily = subfamily_instance
            product_instance.supplier = supplier_instance

            product_instance.save()

            return redirect('inventory:product_list')

        else:
            return HttpResponseBadRequest("Invalid form data. Please check the submitted information.")

    else:
        product_form = ProductForm(prefix='product')

    return render(request, 'inventory/add_product.html', {'product_form': product_form})

#edit_subfamily:
def edit_subfamily(request, pk):
    subfamily_instance = get_object_or_404(subfamily, pk=pk)
    if request.method == 'POST':
        subfamily_form = SubFamilyEditForm(request.POST, instance=subfamily_instance)
        if subfamily_form.is_valid():
            subfamily_form.save()
            return redirect('inventory:subfamily_list')
    else:
        subfamily_form = SubFamilyEditForm(instance=subfamily_instance)
    return render(request, 'inventory/edit_subfamily.html',{'subfamily_form':subfamily_form,'subfamily_instance': subfamily_instance})


#delete_subfamily:
def delete_subfamily(request, pk):
    subfamily_instance = get_object_or_404(subfamily, pk=pk)

    if request.method == 'POST':
        subfamily_instance.delete()
        return redirect ('inventory:subfamily_list')

    return render(request, 'inventory/delete_subfamily.html', {'subfamily': subfamily_instance})


#edit_product:
def edit_product(request,pk):
    prod_instance = get_object_or_404(product, pk = pk)
    if request.method == 'POST':
        form = ProductForm(request.POST, instance=prod_instance)
        if form.is_valid():
            form.save()
            return redirect('inventory:product_list')
    else:
        form = ProductForm(instance=prod_instance)
    return render(request, 'inventory/edit_product.html',{'form':form,'product': prod_instance})

#delete_product:

def delete_product(request, pk):
    prod_instance = get_object_or_404(product, pk = pk)

    if request.method == 'POST':
        prod_instance.delete()
        return redirect('inventory:product_list')

    return render(request, 'inventory/delete_product.html', {'product': prod_instance})


def generate_label(request, pk):
    try:
        # Retrieve the product based on the product_id
        product_instance = get_object_or_404(product, pk=pk)

        # Generate SKUlabe
        sku, _ = generate_sku(product_instance.product_name, product_instance.product_id, product_instance.product_reference)

        # Create an image for the label
        label_image = generate_label_image(product_instance, sku)

        if label_image is None:
            # Handle the case where barcode generation fails
            return HttpResponse("Barcode generation failed. Please check your data.")

        # Save the label image to BytesIO
        label_image_buffer = BytesIO()
        label_image.save(label_image_buffer, format='PNG')
        label_image_buffer.seek(0)

        # Save the label image to a file on the server

        

        # Encode the label image to base64
        barcode_image_base64 = base64.b64encode(label_image_buffer.read()).decode('utf-8')

        # Pass the image and SKU directly to the print_label function
        if 'print' in request.GET:
            return print_label(request, pk, product_instance, sku=sku)

        context = {
            'product': product_instance,
            'sku': sku,
            'label_image_base64': barcode_image_base64,
        }

        return render(request, 'inventory/generate_label_preview.html', context)

    except BarcodeError as e:
        # Handle BarcodeError
        return HttpResponse(f"Barcode generation failed. Error: {e}")
    except Exception as e:
        # Handle other unexpected errors
        return HttpResponse(f"An unexpected error occurred. Error: {e}")
    
    

def print_label(request, pk, product_instance, sku, dpi=600):
    try:
        product_instance = product.objects.get(pk=pk)

        # Generate the label image
        label_image = generate_label_image(product_instance, sku, dpi)

        # Create a PDF document
        response = HttpResponse(content_type='application/pdf')
        response['Content-Disposition'] = 'inline; filename="labels_{pk}.pdf"'

        # Create a canvas for drawing on the PDF
        p = canvas.Canvas(response, pagesize=(label_image.width, label_image.height))


        label_image_path = os.path.join(settings.MEDIA_ROOT, 'images', f"label_{sku}.png")
        label_image.save(label_image_path, format='PNG')
        p.drawInlineImage(label_image, 0,0)


        # Close the PDF canvas
        p.save()



        return response
    

    except product.DoesNotExist:
        return HttpResponse("Product not found.")
    except Exception as e:
        return HttpResponse(f"An unexpected error occurred. Error: {e}")


def generate_label_image(product_instance, sku, dpi=600):
    # Calculate the size of the image in inches based on the desired DPI
    width_inches = 1600 / dpi
    height_inches = 804 / dpi

    # Create an image for the label with higher DPI
    image = Image.new('RGBA', (int(width_inches * dpi), int(height_inches * dpi)), (255, 255, 255, 255))
    # Set the DPI of the image
    image.info['dpi'] = (dpi, dpi)

    # Generate the barcode with Code 128
    barcode_value = sku
    code128 = Code128(barcode_value, writer=ImageWriter())

    # Render the barcode and draw it on the image
    barcode_image = code128.render()
    barcode_image = barcode_image.convert('RGBA')

    # Resize the barcode image to fit the label dimensions
    barcode_image = barcode_image.resize((int(1200), int(600)))

    # Draw the barcode on the image
    image.paste(barcode_image, (int(40 * dpi / 72), int(20 * dpi / 72)))

    # Load fonts for text

inventory_management/inventory/templates/inventory/add_family.html
<!-- inventory/templates/inventory/add_family.html -->
{% extends 'inventory/base.html' %}

{% block content %}
<div class="container">
  <h2>Add Family</h2>
  <form method="post" action="{% url 'inventory:add_family' %}">
    {% csrf_token %}
    {{ family_form.as_p }}
    <button type="submit">Add Family</button>
  </form>
  <a href="{% url 'inventory:family_list' %}">Back to Family List</a>
 </div>
{% endblock %}

inventory_management/inventory/templates/inventory/add_product.html
<!-- inventory/templates/inventory/add_product.html -->
{% extends 'inventory/base.html' %}

{% block content %}
<div class="form-group">
  <h2>Add Product</h2>
  <form method="post" action="{% url 'inventory:add_product' %}" class="container">
    {% csrf_token %}

    <div class="form-row">
      <div class="form-group col-md-6">
        <label for="{{ product_form.prefix }}-{{ product_form.family.id_for_label }}">Category:</label>
        {{ product_form.family }}
      </div>
      <div class="form-group col-md-6">
        <label for="{{ product_form.prefix }}-{{ product_form.subfamily.id_for_label }}">Sub-category:</label>
        {{ product_form.subfamily }}
      </div>
      <div class="form-group col-md-6">
        <label for="{{ product_form.prefix }}-{{ product_form.supplier.id_for_label }}">Supplier:</label>
        {{ product_form.supplier }}
      </div>
    </div>

    <div class="form-row">
      <div class="form-group col-md-6">
        <label for="{{ product_form.prefix }}-{{ product_form.product_name.id_for_label }}">Name:</label>
        {{ product_form.product_name }}
      </div>
      <!-- <div class="form-group col-md-6">
        <label for="{{ product_form.prefix }}-{{ product_form.product_size.id_for_label }}">Size:</label>
        {{ product_form.product_size }}
      </div>
    </div>

    <div class="form-row">
      <div class="form-group col-md-6">
        <label for="{{ product_form.prefix }}-{{ product_form.color.id_for_label }}">Color:</label>
        {{ product_form.color }}
      </div> -->
      <div class="form-group col-md-6">
        <label for="{{ product_form.prefix }}-{{ product_form.product_price_sell.id_for_label }}">Price Sell:</label>
        {{ product_form.product_price_sell }}
      </div>
    </div>

    <div class="form-row">
      <div class="form-group col-md-6">
        <label for="{{ product_form.prefix }}-{{ product_form.product_price_buy.id_for_label }}">Price Buy:</label>
        {{ product_form.product_price_buy }}
      </div>
      <div class="form-group col-md-6">
        <label for="{{ product_form.prefix }}-{{ product_form.product_reference.id_for_label }}">Ref:</label>
        {{ product_form.product_reference }}
      </div>
    </div>

    <div class="form-row">
      <div class="form-group col-md-6">
        <label for="{{ product_form.prefix }}-{{ product_form.product_quantity.id_for_label }}">Quantity:</label>
        {{ product_form.product_quantity }}
      </div>
    </div>

    <button type="submit" class="btn btn-primary">Add Product</button>
    <a href="{% url 'inventory:product_list' %}" class="btn btn-secondary">Back to Product List</a>
  </form>
</div>
{% endblock %}

inventory_management/inventory/templates/inventory/add_subfamily.html
{% extends 'inventory/base.html' %}

{% block content %}
<div class="container">
  <h2>Add SubFamily</h2>
  <form method="post" action="{% url 'inventory:add_subfamily' %}">
    {% csrf_token %}
    {{ subfamily_form.as_p }}
    <button type="submit">Add SubFamily</button>
  </form>
  <a href="{% url 'inventory:subfamily_list' %}">Back to SubFamily List</a>
 </div>
{% endblock %}

inventory_management/inventory/templates/inventory/delete_product.html
<!-- inventory/templates/inventory/delete_product.html -->
{% extends 'inventory/base.html' %}
{% block content %}
  <h2>Delete Product</h2>
  <p>Are you sure you want to delete "{{ product.name }}"?</p>
  <form method="post" action="{% url 'inventory:delete_product' pk=product.pk %}">
    {% csrf_token %}
    <button type="submit">Delete</button>
  </form>
  <a href="{% url 'inventory:product_list' %}">Cancel</a>
{% endblock %}

inventory_management/inventory/templates/inventory/delete_subfamily.html
<!-- inventory/templates/inventory/delete_subfamily.html -->
{% extends 'inventory/base.html' %}
{% block content %}
  <h2>Delete Subfamily</h2>
  <p>Are you sure you want to delete "{{ subfamily.name }}"?</p>
  <form method="post" action="{% url 'inventory:delete_subfamily' pk=subfamily.pk %}">
    {% csrf_token %}
    <button type="submit">Delete</button>
  </form>
  <a href="{% url 'inventory:subfamily_list' %}">Cancel</a>
{% endblock %}

inventory_management/inventory/templates/inventory/edit_product.html
<!-- inventory/templates/inventory/edit_product.html -->
{% extends 'inventory/base.html' %}

{% block content %}
  <h2>Edit Product</h2>
  <form method="post" action="{% url 'inventory:edit_product' pk=product.pk %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save Changes</button>
  </form>
  <a href="{% url 'inventory:product_list' %}">Back to Product List</a>
{% endblock %}

inventory_management/inventory/templates/inventory/edit_subfamily.html
<!-- inventory/templates/inventory/edit_subfamily.html -->
{% extends 'inventory/base.html' %}

{% block content %}
  <h2>Edit Subfamily</h2>
  <form method="post" action="{% url 'inventory:edit_subfamily' pk=subfamily_instance.pk %}">
    {% csrf_token %}
    {{ subfamily_form.as_p }}
    <button type="submit">Save Changes</button>
  </form>
  <a href="{% url 'inventory:subfamily_list' %}">Back to Subfamily List</a>
{% endblock %}

inventory_management/inventory/templates/inventory/family_list.html
{% extends 'inventory/base.html' %}

{% block content %}
  <h2>family List</h2>
  <ul>
    {% for family in families %}
      <li>{{ family.family_name }}
      </li>
    {% endfor %}
  </ul>
  <a href="{% url 'inventory:add_family' %}">Add Family</a>
{% endblock %}

inventory_management/inventory/templates/inventory/generate_label_preview.html
<!-- templates/inventory/generate_label_preview.html -->
{% extends 'inventory/base.html' %}

{% block content %}
  <h2>Label Preview</h2>
  <p>Product Name: {{ product.product_name }}</p>
  <p>Price: {{ product.product_price_sell }}</p>
  <p>Reference: {{ product.product_reference }}</p>
  <img src="data:image/png;base64,{{ label_image_base64 }}" alt="Label Preview" style="max-width: 50%; height: auto;">
  <p>SKU: {{ sku }}</p>
  <button onclick="printLabel()">Print Label</button>
  
  <script>
    function printLabel() {
      // Open a new window with the print-friendly version
      var printWindow = window.open("{% url 'inventory:generate_label' pk=product.pk %}?print=1");

      // Add an event listener for when the window finishes loading
      printWindow.onload = function() {
        // Trigger the print dialog
        printWindow.print();
      };
    }
  </script>
{% endblock %}

inventory_management/inventory/templates/inventory/index.html
<!-- inventory/templates/inventory/index.html -->
{% extends 'inventory/base.html' %}

{% block content %}
  <h2>Inventory Management Dashboard</h2>
  <p>Welcome to the Inventory Management System. Choose an option:</p>
  <ul>
    <li><a href="{% url 'inventory:product_list' %}">View Product List</a></li>
    <li><a href="{% url 'inventory:add_product' %}">Add a New Product</a></li>
    <li><a href="{% url 'inventory:add_family' %}">Add a New Family</a></li>
    <li><a href="{% url 'inventory:add_subfamily' %}">Add a New subfamily</a></li>
    <li><a href="{% url 'inventory:subfamily_list' %}">View Subfamily List</a></li>
    <li><a href="{% url 'srm:supplier_list' %}">View Supplier List</a></li>
    <li><a href="{% url 'srm:add_supplier' %}">Add a new Supplier</a></li>


  </ul>
{% endblock %}

inventory_management/inventory/templates/inventory/label_preview.html
<!-- templates/inventory/label_preview.html -->
{% extends 'inventory/base.html' %}

{% block content %}
  <h2>Label Preview</h2>
  <p>Product Name: {{ product.product_name }}</p>
  <p>Price: {{ product.product_price_sell }}</p>
  <p>Reference: {{ product.product_reference }}</p>
  <img src="data:image/png;base64,{{ label_image_base64 }}" alt="Label Preview">
  <p>SKU: {{ sku }}</p>

  <button onclick="printLabel()">Print Label</button>

  <script>
    function printLabel() {
      // Open a new window with the print-friendly version
      var printWindow = window.open("{% url 'inventory:generate_label_preview' pk=product.pk %}?print=1");

      // Add an event listener for when the window finishes loading
      printWindow.onload = function() {
        // Trigger the print dialog
        printWindow.print();
      };
    }
  </script>
{% endblock %}

inventory_management/inventory/templates/inventory/label_template.html
<!-- label_template.html -->

<html>
<head>
    <style>
        /* Your styles here */
    </style>
</head>
<body>
    <div>
        <img src="{{ product.barcode.url }}" alt="Barcode">
        <p>SKU: {{ product.sku }}</p>
        <p>Name: {{ product.name }}</p>
        <p>Price: ${{ product.price }}</p>
        <!-- Add other fields as needed -->
    </div>
</body>
</html>

inventory_management/inventory/templates/inventory/product_list.html
<!-- inventory/templates/inventory/product_list.html -->

{% extends 'inventory/base.html' %}

{% block content %}
  <table class="table table-striped table-dark">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Name</th>
        <th scope="col">Size</th>
        <th scope="col">Edit</th>
        <th scope="col">Delete</th>
        <th scope="col">Generate Label</th>
      </tr>
    </thead>
    <tbody>
      {% for product in products %}
        <tr>
          <th scope="row">{{ product.product_id }}</th>
          <td>{{ product.product_name }}</td>
          <td>{{ product.product_size }}</td>
          <td><a href="{% url 'inventory:edit_product' pk=product.pk %}">Edit</a></td>
          <td><a href="{% url 'inventory:delete_product' pk=product.pk %}">Delete</a></td>
          <td><a href="#" onclick="openLabelPreview('{{ product.product_name }}', '{{ product.product_price_sell }}', '{{ product.product_reference }}', '{{ product.pk }}');">Generate Label</a></td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  <a href="{% url 'inventory:add_product' %}">Add Product</a>

  <script>
    function openLabelPreview(productName, productPriceSell, productReference, productId) {
      // Open a new window with the label preview
      var labelPreviewWindow = window.open(
        "/generate_label/" + productId + "/?preview=1&product_name=" +
        encodeURIComponent(productName) +
        "&product_price_sell=" +
        encodeURIComponent(productPriceSell) +
        "&product_reference=" +
        encodeURIComponent(productReference),
        "LabelPreview",
        "width=600,height=400"
      );
      // Add an event listener for when the window is closed
      labelPreviewWindow.onunload = function() {
        // Do any cleanup or additional actions if needed
      };
    }
  </script>
{% endblock %}

inventory_management/inventory/templates/inventory/subfamily_list.html
<!-- inventory/templates/inventory/subfamily_list.html -->
{% extends 'inventory/base.html' %}

{% block content %}
  <h2>subfamily List</h2>
  <ul>
    {% for subfamily in subfamilies %}
      <li>{{ subfamily.subfamily_name }}
      <a href="{% url 'inventory:edit_subfamily' pk=subfamily.pk|safe %}">Edit</a>
      <a href="{% url 'inventory:delete_subfamily' pk=subfamily.pk|safe %}">Delete</a>
      </li>
    {% endfor %}
  </ul>
  <a href="{% url 'inventory:add_subfamily' %}">Add SubFamily</a>
  <a href="{% url 'inventory:add_family' %}">Add Family</a>
{% endblock %}